name: Run `kodumisto.py` when Issue gets 'kodumisto' label

on:
  issues:
    types:
      - labeled

jobs:
  run_python_script:
    if: github.event.label.name == 'kodumisto'
    runs-on: ubuntu-latest
    environment: env-secrets
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-kodumisto-github-actions.txt

    - name: Execute Python script
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
      run: python kodumisto.py ${{ github.event.issue.number }} ${{ github.repository_owner }} ${{ github.event.repository.name }}
